export const MOVIE_DATA_REQUEST = 'MOVIE_DATA_REQUEST'
export const MOVIE_DATA_SUCCESS = 'MOVIE_DATA_SUCCESS'
export const MOVIE_DATA_FAILURE = 'MOVIE_DATA_FAILURE'

export const MOVIE_DETAILS_REQUEST = 'MOVIE_DETAILS_REQUEST'
export const MOVIE_DETAILS_SUCCESS = 'MOVIE_DETAILS_SUCCESS'
export const MOVIE_DETAILS_FAILURE = 'MOVIE_DETAILS_FAILURE'

export const FAVOURITEMOVIE_DETAILS_REQUEST = 'FAVOURITEMOVIE_DETAILS_REQUEST'
export const FAVOURITEMOVIE_DETAILS_SUCCESS = 'FAVOURITEMOVIE_DETAILS_SUCCESS'
export const FAVOURITEMOVIE_DETAILS_FAILURE = 'FAVOURITEMOVIE_DETAILS_FAILURE'

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE"


export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE"

export const ADD_FAVOURITE = "ADD_FAVOURITE"
export const REMOVE_FAVOURITE = "REMOVE_FAVOURITE"

export const FAVOURITE_REQUEST = 'FAVOURITE_REQUEST'
export const FAVOURITE_SUCCESS = 'FAVOURITE_SUCCESS'
export const FAVOURITE_FAILURE = 'FAVOURITE_FAILURE'
